### ISSUE TITLE
Typechov1.2.0-rc.1用不了

### ISSUE THREAD

**Issue by 52qiangzai** [gaobinzhan/CommentPush#14]
Typechov1.2.0-rc.1用不了

![WW%$S`A0I0CRR@P{HCX~63M](https://user-images.githubusercontent.com/63764939/134452211-06280fd8-ee37-40a2-881b-abdfe211c88f.png)

**Comment by Player626** [comment]
通过typecho的版本号来看 应该是做了不兼容的更新导致的

**Comment by KurococLiu** [comment]
> 通过typecho的版本号来看 应该是做了不兼容的更新导致的

debug信息：

Argument 1 passed to Typecho\Validate::required() must be of the type string or null, array given
TypeError: Argument 1 passed to Typecho\Validate::required() must be of the type string or null, array given in /www/wwwroot/blog/var/Typecho/Validate.php:326
Stack trace:
#0 [internal function]: Typecho\Validate->required(Array)
#1 /www/wwwroot/blog/var/Typecho/Validate.php(287): call_user_func_array(Array, Array)
#2 /www/wwwroot/blog/var/Typecho/Widget/Helper/Form.php(185): Typecho\Validate->run(Array, Array)
#3 /www/wwwroot/blog/var/Widget/Plugins/Edit.php(284): Typecho\Widget\Helper\Form->validate()
#4 /www/wwwroot/blog/var/Widget/Plugins/Edit.php(315): Widget\Plugins\Edit->config('CommentPush')
#5 /www/wwwroot/blog/var/Widget/Action.php(71): Widget\Plugins\Edit->action()
#6 /www/wwwroot/blog/var/Typecho/Widget.php(155): Widget\Action->execute()
#7 /www/wwwroot/blog/var/Typecho/Router.php(96): Typecho\Widget::widget('\\Widget\\Action', NULL, Array)
#8 /www/wwwroot/blog/index.php(23): Typecho\Router::dispatch()
#9 {main}

**Comment by zuohl** [comment]
> 通过typecho的版本号来看 应该是做了不兼容的更新导致的

能辛苦更新一下吗

**Comment by Player626** [comment]
https://github.com/Stitch-June/CommentPush/releases/tag/2.0.0

**Comment by qinians** [comment]
刚才测试，还是不行

**Comment by asplun** [comment]
问题没有解决

**Comment by Sagit-chu** [comment]
1.2.0-rc.2也是一样的报错

**Comment by jiajiechan** [comment]
修改AliYunEmailService.php和SmtpService.php
把 widget = new $className(Typecho_Request::getInstance(), Typecho_Widget_Helper_Empty::getInstance());
换成 $widget = $className::alloc();

教程来源https://blog.tsutsu.one/archives/350/
